import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	card: {
		backgroundColor: "white",
		borderRadius: 16,
		shadowOpacity: 0.2,
		shadowRadius: 4,
		shadowColor: "black",
		shadowOffset: {
			height: 0,
			width: 0,
		},
		elevation: 1,
		marginVertical: 20,
	},
	image: {
		width: "100%",
		aspectRatio: 16 / 9, // Proporção 16:9 (widescreen)
		backgroundColor: "#f5f5f5", // Cor de fundo enquanto carrega
	},
	infoContainer: {
		padding: 16,
	},
	name: {
		fontSize: 22,
		fontWeight: "bold",
	},
	price: {
		fontSize: 16,
		fontWeight: "600",
		marginBottom: 8,
	},
	description: {
		fontSize: 16,
		fontWeight: "400",
		color: "#787878",
		marginBottom: 16,
	},
	imageWarning: {
		fontSize: 12,
		color: "#ff6b6b",
		fontStyle: "italic",
		marginBottom: 8,
	},
	// Estilos do carrinho de compras
	cartContainer: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	cartHeader: {
		backgroundColor: "white",
		paddingVertical: 20,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#e9ecef",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	cartTitle: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#2c3e50",
		textAlign: "center",
	},
	cartItemContainer: {
		backgroundColor: "white",
		marginHorizontal: 16,
		marginVertical: 8,
		borderRadius: 12,
		padding: 16,
		flexDirection: "row",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.08,
		shadowRadius: 8,
		elevation: 2,
	},
	cartItemImage: {
		width: 80,
		height: 80,
		borderRadius: 12,
		backgroundColor: "#f8f9fa",
		marginRight: 16,
	},
	cartItemDetails: {
		flex: 1,
		marginRight: 12,
	},
	cartItemName: {
		fontSize: 16,
		fontWeight: "600",
		color: "#2c3e50",
		marginBottom: 4,
	},
	cartItemPrice: {
		fontSize: 16,
		fontWeight: "bold",
		color: "#e74c3c",
		marginBottom: 8,
	},
	quantityContainer: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
		borderRadius: 25,
		paddingVertical: 4,
		paddingHorizontal: 8,
		minWidth: 100,
	},
	quantityButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: "#3498db",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#3498db",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 3,
	},
	quantityButtonDisabled: {
		backgroundColor: "#bdc3c7",
		shadowOpacity: 0,
		elevation: 0,
	},
	quantityButtonText: {
		color: "white",
		fontSize: 18,
		fontWeight: "bold",
	},
	quantityText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#2c3e50",
		marginHorizontal: 16,
		minWidth: 20,
		textAlign: "center",
	},
	cartSummary: {
		backgroundColor: "white",
		margin: 16,
		borderRadius: 12,
		padding: 20,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 3,
	},
	summaryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 12,
	},
	summaryLabel: {
		fontSize: 16,
		color: "#7f8c8d",
	},
	summaryValue: {
		fontSize: 16,
		fontWeight: "600",
		color: "#2c3e50",
	},
	totalRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: "#e9ecef",
		marginTop: 8,
	},
	totalLabel: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#2c3e50",
	},
	totalValue: {
		fontSize: 20,
		fontWeight: "bold",
		color: "#e74c3c",
	},
	checkoutButton: {
		backgroundColor: "#27ae60",
		margin: 16,
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: "center",
		shadowColor: "#27ae60",
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 5,
	},
	checkoutButtonText: {
		color: "white",
		fontSize: 18,
		fontWeight: "bold",
	},
	emptyCartContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		padding: 40,
	},
	emptyCartText: {
		fontSize: 18,
		color: "#7f8c8d",
		textAlign: "center",
		marginTop: 16,
	},
	emptyCartIcon: {
		fontSize: 64,
		color: "#bdc3c7",
		marginBottom: 16,
	},
	// Estilos da lista de produtos
	productListContainer: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	productListHeader: {
		backgroundColor: "white",
		paddingVertical: 20,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#e9ecef",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	productListTitle: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#2c3e50",
		textAlign: "center",
	},
	productListSubtitle: {
		fontSize: 14,
		color: "#7f8c8d",
		textAlign: "center",
		marginTop: 4,
	},
	productCard: {
		backgroundColor: "white",
		borderRadius: 16,
		marginHorizontal: 16,
		marginVertical: 8,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 3,
		},
		shadowOpacity: 0.12,
		shadowRadius: 8,
		elevation: 4,
		overflow: "hidden",
	},
	productImage: {
		width: "100%",
		height: 200,
		backgroundColor: "#f8f9fa",
	},
	productInfoContainer: {
		padding: 16,
	},
	productName: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#2c3e50",
		marginBottom: 8,
		lineHeight: 24,
	},
	productPrice: {
		fontSize: 20,
		fontWeight: "bold",
		color: "#e74c3c",
		marginBottom: 12,
	},
	productButton: {
		backgroundColor: "#3498db",
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 8,
		alignItems: "center",
		shadowColor: "#3498db",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 3,
	},
	productButtonText: {
		color: "white",
		fontSize: 16,
		fontWeight: "600",
	},
	productBadge: {
		position: "absolute",
		top: 12,
		right: 12,
		backgroundColor: "#e74c3c",
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 12,
		zIndex: 1,
	},
	productBadgeText: {
		color: "white",
		fontSize: 12,
		fontWeight: "bold",
	},
	loadingContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
	},
	loadingText: {
		fontSize: 16,
		color: "#7f8c8d",
		marginTop: 12,
	},
	// Estilos da tela de detalhes do produto
	productDetailContainer: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	productDetailHeader: {
		position: "relative",
		height: 350,
		backgroundColor: "white",
	},
	productDetailImage: {
		width: "100%",
		height: "100%",
		backgroundColor: "#f8f9fa",
	},
	productDetailBackButton: {
		position: "absolute",
		top: 50,
		left: 16,
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: "rgba(255, 255, 255, 0.9)",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 3,
		zIndex: 1,
	},
	productDetailBackButtonText: {
		fontSize: 18,
		color: "#2c3e50",
		fontWeight: "bold",
	},
	productDetailFavoriteButton: {
		position: "absolute",
		top: 50,
		right: 16,
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: "rgba(255, 255, 255, 0.9)",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.2,
		shadowRadius: 4,
		elevation: 3,
		zIndex: 1,
	},
	productDetailContent: {
		flex: 1,
		backgroundColor: "white",
		borderTopLeftRadius: 24,
		borderTopRightRadius: 24,
		marginTop: -24,
		paddingTop: 24,
		paddingHorizontal: 20,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: -2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 5,
	},
	productDetailTitle: {
		fontSize: 26,
		fontWeight: "bold",
		color: "#2c3e50",
		marginBottom: 8,
		lineHeight: 32,
	},
	productDetailPrice: {
		fontSize: 28,
		fontWeight: "bold",
		color: "#e74c3c",
		marginBottom: 16,
	},
	productDetailRating: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 20,
	},
	productDetailStars: {
		flexDirection: "row",
		marginRight: 8,
	},
	productDetailRatingText: {
		fontSize: 14,
		color: "#7f8c8d",
		marginLeft: 4,
	},
	productDetailSection: {
		marginBottom: 24,
	},
	productDetailSectionTitle: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#2c3e50",
		marginBottom: 12,
	},
	productDetailDescription: {
		fontSize: 16,
		color: "#5a5a5a",
		lineHeight: 24,
		textAlign: "justify",
	},
	productDetailFeatures: {
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 8,
	},
	productDetailFeature: {
		backgroundColor: "#ecf0f1",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
		marginBottom: 8,
	},
	productDetailFeatureText: {
		fontSize: 14,
		color: "#2c3e50",
		fontWeight: "500",
	},
	productDetailQuantitySection: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		marginBottom: 24,
	},
	productDetailQuantityLabel: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#2c3e50",
	},
	productDetailQuantityControls: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
		borderRadius: 25,
		paddingVertical: 4,
		paddingHorizontal: 8,
	},
	productDetailQuantityButton: {
		width: 36,
		height: 36,
		borderRadius: 18,
		backgroundColor: "#3498db",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#3498db",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 3,
	},
	productDetailQuantityButtonDisabled: {
		backgroundColor: "#bdc3c7",
		shadowOpacity: 0,
		elevation: 0,
	},
	productDetailQuantityButtonText: {
		color: "white",
		fontSize: 18,
		fontWeight: "bold",
	},
	productDetailQuantityText: {
		fontSize: 18,
		fontWeight: "600",
		color: "#2c3e50",
		marginHorizontal: 20,
		minWidth: 30,
		textAlign: "center",
	},
	productDetailFooter: {
		flexDirection: "row",
		padding: 20,
		backgroundColor: "white",
		borderTopWidth: 1,
		borderTopColor: "#e9ecef",
		gap: 12,
	},
	productDetailAddToCartButton: {
		flex: 1,
		backgroundColor: "#27ae60",
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: "center",
		shadowColor: "#27ae60",
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 5,
	},
	productDetailAddToCartButtonText: {
		color: "white",
		fontSize: 18,
		fontWeight: "bold",
	},
	productDetailFavoriteActionButton: {
		width: 56,
		height: 56,
		borderRadius: 12,
		backgroundColor: "#ecf0f1",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "#bdc3c7",
	},
	productDetailAvailabilityBadge: {
		backgroundColor: "#27ae60",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 16,
		alignSelf: "flex-start",
		marginBottom: 16,
	},
	productDetailAvailabilityText: {
		color: "white",
		fontSize: 12,
		fontWeight: "bold",
	},
	// Botão flutuante do carrinho
	floatingCartButton: {
		position: "absolute",
		bottom: 20,
		right: 20,
		width: 60,
		height: 60,
		borderRadius: 30,
		backgroundColor: "#e74c3c",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#e74c3c",
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.4,
		shadowRadius: 8,
		elevation: 8,
		zIndex: 1000,
	},
	floatingCartButtonText: {
		color: "white",
		fontSize: 24,
	},
	floatingCartBadge: {
		position: "absolute",
		top: -5,
		right: -5,
		backgroundColor: "#27ae60",
		width: 24,
		height: 24,
		borderRadius: 12,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 2,
		borderColor: "white",
	},
	floatingCartBadgeText: {
		color: "white",
		fontSize: 12,
		fontWeight: "bold",
	},
});
