import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	card: {
		backgroundColor: "white",
		borderRadius: 16,
		shadowOpacity: 0.2,
		shadowRadius: 4,
		shadowColor: "black",
		shadowOffset: {
			height: 0,
			width: 0,
		},
		elevation: 1,
		marginVertical: 20,
	},
	image: {
		width: "100%",
		aspectRatio: 16 / 9, // Proporção 16:9 (widescreen)
		backgroundColor: "#f5f5f5", // Cor de fundo enquanto carrega
	},
	infoContainer: {
		padding: 16,
	},
	name: {
		fontSize: 22,
		fontWeight: "bold",
	},
	price: {
		fontSize: 16,
		fontWeight: "600",
		marginBottom: 8,
	},
	description: {
		fontSize: 16,
		fontWeight: "400",
		color: "#787878",
		marginBottom: 16,
	},
	imageWarning: {
		fontSize: 12,
		color: "#ff6b6b",
		fontStyle: "italic",
		marginBottom: 8,
	},
	// Estilos do carrinho de compras
	cartContainer: {
		flex: 1,
		backgroundColor: "#f8f9fa",
	},
	cartHeader: {
		backgroundColor: "white",
		paddingVertical: 20,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#e9ecef",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	cartTitle: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#2c3e50",
		textAlign: "center",
	},
	cartItemContainer: {
		backgroundColor: "white",
		marginHorizontal: 16,
		marginVertical: 8,
		borderRadius: 12,
		padding: 16,
		flexDirection: "row",
		alignItems: "center",
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.08,
		shadowRadius: 8,
		elevation: 2,
	},
	cartItemImage: {
		width: 80,
		height: 80,
		borderRadius: 12,
		backgroundColor: "#f8f9fa",
		marginRight: 16,
	},
	cartItemDetails: {
		flex: 1,
		marginRight: 12,
	},
	cartItemName: {
		fontSize: 16,
		fontWeight: "600",
		color: "#2c3e50",
		marginBottom: 4,
	},
	cartItemPrice: {
		fontSize: 16,
		fontWeight: "bold",
		color: "#e74c3c",
		marginBottom: 8,
	},
	quantityContainer: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: "#f8f9fa",
		borderRadius: 25,
		paddingVertical: 4,
		paddingHorizontal: 8,
		minWidth: 100,
	},
	quantityButton: {
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: "#3498db",
		justifyContent: "center",
		alignItems: "center",
		shadowColor: "#3498db",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.3,
		shadowRadius: 4,
		elevation: 3,
	},
	quantityButtonDisabled: {
		backgroundColor: "#bdc3c7",
		shadowOpacity: 0,
		elevation: 0,
	},
	quantityButtonText: {
		color: "white",
		fontSize: 18,
		fontWeight: "bold",
	},
	quantityText: {
		fontSize: 16,
		fontWeight: "600",
		color: "#2c3e50",
		marginHorizontal: 16,
		minWidth: 20,
		textAlign: "center",
	},
	cartSummary: {
		backgroundColor: "white",
		margin: 16,
		borderRadius: 12,
		padding: 20,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.1,
		shadowRadius: 8,
		elevation: 3,
	},
	summaryRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 12,
	},
	summaryLabel: {
		fontSize: 16,
		color: "#7f8c8d",
	},
	summaryValue: {
		fontSize: 16,
		fontWeight: "600",
		color: "#2c3e50",
	},
	totalRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: "#e9ecef",
		marginTop: 8,
	},
	totalLabel: {
		fontSize: 18,
		fontWeight: "bold",
		color: "#2c3e50",
	},
	totalValue: {
		fontSize: 20,
		fontWeight: "bold",
		color: "#e74c3c",
	},
	checkoutButton: {
		backgroundColor: "#27ae60",
		margin: 16,
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: "center",
		shadowColor: "#27ae60",
		shadowOffset: {
			width: 0,
			height: 4,
		},
		shadowOpacity: 0.3,
		shadowRadius: 8,
		elevation: 5,
	},
	checkoutButtonText: {
		color: "white",
		fontSize: 18,
		fontWeight: "bold",
	},
	emptyCartContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		padding: 40,
	},
	emptyCartText: {
		fontSize: 18,
		color: "#7f8c8d",
		textAlign: "center",
		marginTop: 16,
	},
	emptyCartIcon: {
		fontSize: 64,
		color: "#bdc3c7",
		marginBottom: 16,
	},
});
